import { Assessment, AssessmentSection, AssessmentQuestion } from '@/types/assessment';

export const sampleAssessments: Omit<Assessment, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: "Frontend Developer Assessment",
    description: "Comprehensive assessment for frontend developer candidates covering HTML, CSS, JavaScript, and React.",
    sections: [
      {
        id: "section_1",
        title: "Technical Skills",
        description: "Evaluate technical knowledge and problem-solving abilities",
        order: 0,
        questions: [
          {
            id: "q1",
            type: "single-choice",
            title: "What is the primary purpose of React hooks?",
            description: "Choose the most accurate answer about React hooks.",
            required: true,
            order: 0,
            options: [
              { id: "opt1", label: "To manage component state and side effects", value: "state_side_effects", order: 0 },
              { id: "opt2", label: "To replace class components entirely", value: "replace_class", order: 1 },
              { id: "opt3", label: "To improve performance only", value: "performance", order: 2 },
              { id: "opt4", label: "To handle routing in React applications", value: "routing", order: 3 },
            ],
          },
          {
            id: "q2",
            type: "multi-choice",
            title: "Which of the following are valid CSS positioning values?",
            description: "Select all correct CSS positioning properties.",
            required: true,
            order: 1,
            options: [
              { id: "opt5", label: "static", value: "static", order: 0 },
              { id: "opt6", label: "relative", value: "relative", order: 1 },
              { id: "opt7", label: "absolute", value: "absolute", order: 2 },
              { id: "opt8", label: "floating", value: "floating", order: 3 },
              { id: "opt9", label: "fixed", value: "fixed", order: 4 },
            ],
          },
          {
            id: "q3",
            type: "short-text",
            title: "What does the acronym API stand for?",
            description: "Provide the full form of API.",
            required: true,
            order: 2,
            maxLength: 50,
          },
          {
            id: "q4",
            type: "long-text",
            title: "Explain the concept of closures in JavaScript with an example.",
            description: "Provide a detailed explanation with a code example.",
            required: true,
            order: 3,
            maxLength: 500,
          },
          {
            id: "q5",
            type: "numeric-range",
            title: "How many years of experience do you have with React?",
            description: "Enter your years of experience as a number.",
            required: true,
            order: 4,
            minValue: 0,
            maxValue: 20,
          },
          {
            id: "q6",
            type: "single-choice",
            title: "What is the difference between let, const, and var in JavaScript?",
            description: "Choose the most accurate description of variable declarations.",
            required: true,
            order: 5,
            options: [
              { id: "opt10", label: "let and const are block-scoped, var is function-scoped", value: "block_scoped", order: 0 },
              { id: "opt11", label: "All three are function-scoped", value: "function_scoped", order: 1 },
              { id: "opt12", label: "const can be reassigned, let and var cannot", value: "reassignment", order: 2 },
              { id: "opt13", label: "They are all identical in behavior", value: "identical", order: 3 },
            ],
          },
          {
            id: "q7",
            type: "multi-choice",
            title: "Which of the following are valid HTML5 semantic elements?",
            description: "Select all correct HTML5 semantic elements.",
            required: true,
            order: 6,
            options: [
              { id: "opt14", label: "<header>", value: "header", order: 0 },
              { id: "opt15", label: "<nav>", value: "nav", order: 1 },
              { id: "opt16", label: "<section>", value: "section", order: 2 },
              { id: "opt17", label: "<div>", value: "div", order: 3 },
              { id: "opt18", label: "<article>", value: "article", order: 4 },
            ],
          },
          {
            id: "q8",
            type: "short-text",
            title: "What is the purpose of the virtual DOM in React?",
            description: "Explain the virtual DOM concept briefly.",
            required: true,
            order: 7,
            maxLength: 100,
          },
          {
            id: "q9",
            type: "long-text",
            title: "Describe the difference between controlled and uncontrolled components in React.",
            description: "Provide examples of both types of components.",
            required: true,
            order: 8,
            maxLength: 400,
          },
          {
            id: "q10",
            type: "numeric-range",
            title: "Rate your proficiency with CSS Grid (1-10)",
            description: "Rate your CSS Grid skills from 1 (beginner) to 10 (expert).",
            required: true,
            order: 9,
            minValue: 1,
            maxValue: 10,
          },
        ],
      },
    ],
    isPublished: true,
  },
  {
    title: "UX Designer Assessment",
    description: "Assessment to evaluate UX design skills, user research abilities, and design thinking process.",
    sections: [
      {
        id: "section_3",
        title: "Design Fundamentals",
        description: "Test understanding of design principles and user experience concepts",
        order: 0,
        questions: [
          {
            id: "q11",
            type: "single-choice",
            title: "What is the primary goal of user experience design?",
            description: "Choose the most comprehensive answer.",
            required: true,
            order: 0,
            options: [
              { id: "opt19", label: "To make products look beautiful", value: "beautiful", order: 0 },
              { id: "opt20", label: "To create intuitive and user-centered experiences", value: "user_centered", order: 1 },
              { id: "opt21", label: "To follow the latest design trends", value: "trends", order: 2 },
              { id: "opt22", label: "To reduce development costs", value: "costs", order: 3 },
            ],
          },
          {
            id: "q12",
            type: "multi-choice",
            title: "Which methods are commonly used in user research?",
            description: "Select all valid user research methods.",
            required: true,
            order: 1,
            options: [
              { id: "opt23", label: "User interviews", value: "interviews", order: 0 },
              { id: "opt24", label: "Usability testing", value: "usability", order: 1 },
              { id: "opt25", label: "Surveys", value: "surveys", order: 2 },
              { id: "opt26", label: "A/B testing", value: "ab_testing", order: 3 },
              { id: "opt27", label: "Code review", value: "code_review", order: 4 },
            ],
          },
          {
            id: "q13",
            type: "long-text",
            title: "Describe your design process from research to final implementation.",
            description: "Walk through your typical design workflow and methodology.",
            required: true,
            order: 2,
            maxLength: 800,
          },
          {
            id: "q14",
            type: "single-choice",
            title: "What is the difference between UX and UI design?",
            description: "Choose the most accurate distinction.",
            required: true,
            order: 3,
            options: [
              { id: "opt28", label: "UX focuses on user experience, UI focuses on visual design", value: "ux_ui", order: 0 },
              { id: "opt29", label: "They are exactly the same thing", value: "same", order: 1 },
              { id: "opt30", label: "UX is about coding, UI is about design", value: "coding", order: 2 },
              { id: "opt31", label: "UI is more important than UX", value: "ui_important", order: 3 },
            ],
          },
          {
            id: "q15",
            type: "short-text",
            title: "What does 'accessibility' mean in design?",
            description: "Define accessibility in the context of UX design.",
            required: true,
            order: 4,
            maxLength: 150,
          },
          {
            id: "q16",
            type: "multi-choice",
            title: "Which tools are commonly used for prototyping?",
            description: "Select all valid prototyping tools.",
            required: true,
            order: 5,
            options: [
              { id: "opt32", label: "Figma", value: "figma", order: 0 },
              { id: "opt33", label: "Sketch", value: "sketch", order: 1 },
              { id: "opt34", label: "Adobe XD", value: "adobe_xd", order: 2 },
              { id: "opt35", label: "InVision", value: "invision", order: 3 },
              { id: "opt36", label: "Microsoft Word", value: "word", order: 4 },
            ],
          },
          {
            id: "q17",
            type: "numeric-range",
            title: "How many years of UX design experience do you have?",
            description: "Enter your years of experience in UX design.",
            required: true,
            order: 6,
            minValue: 0,
            maxValue: 15,
          },
          {
            id: "q18",
            type: "long-text",
            title: "Explain the concept of 'user personas' and how you create them.",
            description: "Describe the process and importance of user personas.",
            required: true,
            order: 7,
            maxLength: 600,
          },
          {
            id: "q19",
            type: "single-choice",
            title: "What is the purpose of wireframing in the design process?",
            description: "Choose the most accurate description of wireframing.",
            required: true,
            order: 8,
            options: [
              { id: "opt37", label: "To create high-fidelity visual designs", value: "high_fidelity", order: 0 },
              { id: "opt38", label: "To plan layout and structure before visual design", value: "layout_structure", order: 1 },
              { id: "opt39", label: "To write code for the application", value: "write_code", order: 2 },
              { id: "opt40", label: "To test user interactions", value: "test_interactions", order: 3 },
            ],
          },
          {
            id: "q20",
            type: "short-text",
            title: "What is the difference between qualitative and quantitative research?",
            description: "Briefly explain the distinction between these research types.",
            required: true,
            order: 9,
            maxLength: 200,
          },
        ],
      },
    ],
    isPublished: false,
  },
  {
    title: "Product Manager Assessment",
    description: "Evaluate product management skills, strategic thinking, and stakeholder management abilities.",
    sections: [
      {
        id: "section_4",
        title: "Product Strategy",
        description: "Test strategic thinking and product vision",
        order: 0,
        questions: [
          {
            id: "q21",
            type: "single-choice",
            title: "What is the primary responsibility of a Product Manager?",
            description: "Choose the most accurate description.",
            required: true,
            order: 0,
            options: [
              { id: "opt41", label: "To write code and develop features", value: "code", order: 0 },
              { id: "opt42", label: "To define product vision and strategy", value: "strategy", order: 1 },
              { id: "opt43", label: "To manage the development team", value: "team_management", order: 2 },
              { id: "opt44", label: "To handle customer support", value: "support", order: 3 },
            ],
          },
          {
            id: "q22",
            type: "numeric-range",
            title: "How many years of product management experience do you have?",
            description: "Enter your years of experience.",
            required: true,
            order: 1,
            minValue: 0,
            maxValue: 15,
          },
          {
            id: "q23",
            type: "long-text",
            title: "Describe a challenging product decision you had to make and how you handled it.",
            description: "Provide a detailed example of your decision-making process.",
            required: true,
            order: 2,
            maxLength: 1000,
          },
          {
            id: "q24",
            type: "multi-choice",
            title: "Which metrics are commonly used to measure product success?",
            description: "Select all relevant product metrics.",
            required: true,
            order: 3,
            options: [
              { id: "opt45", label: "Monthly Active Users (MAU)", value: "mau", order: 0 },
              { id: "opt46", label: "Customer Acquisition Cost (CAC)", value: "cac", order: 1 },
              { id: "opt47", label: "Net Promoter Score (NPS)", value: "nps", order: 2 },
              { id: "opt48", label: "Revenue per User", value: "revenue_per_user", order: 3 },
              { id: "opt49", label: "Code lines written", value: "code_lines", order: 4 },
            ],
          },
          {
            id: "q25",
            type: "short-text",
            title: "What is the difference between a product roadmap and a product backlog?",
            description: "Briefly explain the distinction between these concepts.",
            required: true,
            order: 4,
            maxLength: 200,
          },
          {
            id: "q26",
            type: "single-choice",
            title: "What is the primary purpose of user stories in product development?",
            description: "Choose the most accurate description of user stories.",
            required: true,
            order: 5,
            options: [
              { id: "opt50", label: "To write technical specifications", value: "tech_specs", order: 0 },
              { id: "opt51", label: "To define features from the user's perspective", value: "user_perspective", order: 1 },
              { id: "opt52", label: "To track development time", value: "track_time", order: 2 },
              { id: "opt53", label: "To manage team schedules", value: "manage_schedules", order: 3 },
            ],
          },
          {
            id: "q27",
            type: "long-text",
            title: "How do you prioritize features when resources are limited?",
            description: "Describe your approach to feature prioritization.",
            required: true,
            order: 6,
            maxLength: 500,
          },
          {
            id: "q28",
            type: "multi-choice",
            title: "Which stakeholders are typically involved in product development?",
            description: "Select all relevant stakeholders.",
            required: true,
            order: 7,
            options: [
              { id: "opt54", label: "Engineering team", value: "engineering", order: 0 },
              { id: "opt55", label: "Design team", value: "design", order: 1 },
              { id: "opt56", label: "Marketing team", value: "marketing", order: 2 },
              { id: "opt57", label: "Sales team", value: "sales", order: 3 },
              { id: "opt58", label: "Customers", value: "customers", order: 4 },
            ],
          },
          {
            id: "q29",
            type: "numeric-range",
            title: "Rate your experience with agile methodologies (1-10)",
            description: "Rate your familiarity with agile practices from 1 (beginner) to 10 (expert).",
            required: true,
            order: 8,
            minValue: 1,
            maxValue: 10,
          },
          {
            id: "q30",
            type: "short-text",
            title: "What is the purpose of A/B testing in product management?",
            description: "Explain how A/B testing helps in product decisions.",
            required: true,
            order: 9,
            maxLength: 150,
          },
        ],
      },
    ],
    isPublished: true,
  },
];

export const createSampleAssessments = () => {
  return sampleAssessments.map(assessment => ({
    ...assessment,
    id: Math.random().toString(36).substr(2, 9),
    createdAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000), // Random date within last 30 days
    updatedAt: new Date(),
  }));
};
